/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: martinjario (https://sketchfab.com/martinjario)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/skull-downloadable-1a9db900738d44298b0bc59f68123393
title: Skull downloadable
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Model = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={materials.defaultMat}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/scene.gltf");
