/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karol Miklas (https://sketchfab.com/karolmiklas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-zuk-3d-model-bb4OJb5V4L0hgYjM3vtGvPB7ZMt
title: (FREE) Żuk 3D model
*/

import { useGLTF } from "@react-three/drei";

export const Model = (props) => {
  const { nodes } = useGLTF("/scene.gltf");
  console.log(nodes);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 0]}>
          <group scale={0.93}>
            <mesh
              geometry={nodes.Plane018_0.geometry}
              material={nodes.Plane018_0.material}
            />
          </group>
          <group
            position={[-0.38, -0.81, 0.51]}
            rotation={[1.03, -0.46, -0.93]}
            scale={[0.29, 0.29, 0.29]}
          />
          <group scale={0.93}>
            <mesh
              geometry={nodes.Plane003_0.geometry}
              material={nodes.Plane003_0.material}
            />
          </group>
          <group
            position={[-0.38, -0.81, 0.51]}
            rotation={[-1.06, 0.83, -0.56]}
            scale={[0.29, 0.29, 0.29]}
          />
          <group
            position={[-0.8, 0.45, 0.42]}
            rotation={[-1.94, -0.24, 2.36]}
            scale={[0.29, 0.29, 0.29]}
          />
          <group
            position={[-0.38, -0.81, 0.51]}
            rotation={[-2.51, -0.09, 0.56]}
            scale={[0.29, 0.29, 0.29]}
          />
          <group
            position={[-0.38, -0.81, 0.51]}
            rotation={[-1.12, -0.72, -1.28]}
            scale={[0.29, 0.29, 0.29]}
          />
          <group
            position={[-0.33, 1.21, 0.57]}
            rotation={[-1.94, -0.24, 2.36]}
            scale={[0.29, 0.29, 0.29]}
          />
          <group
            position={[1.3, -0.24, 0.62]}
            rotation={[-1.94, -0.24, 2.36]}
            scale={[0.29, 0.29, 0.29]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/scene.gltf");
